<?php

$relation = [
    // other classes
    '.container,'  => '.container, .grid-container,',
    '.container {' => '.container, .grid-container {',
    '.row,'     => '.row, grid-offset,',
    '.row {'    => '.row, .grid-offset {',
    // lg
    '.col-lg-1,'        => '.col-lg-1, .grid-5, .grid-10,',
    '.col-lg-1 {'       => '.col-lg-1, .grid-5, .grid-10 {',
    '.col-lg-2,'        => '.col-lg-2, .grid-15,',
    '.col-lg-2 {'       => '.col-lg-2, .grid-15 {',
    '.col-lg-3,'        => '.col-lg-3, .grid-20, .grid-25,',
    '.col-lg-3 {'       => '.col-lg-3, .grid-20, .grid-25 {',
    '.col-lg-4,'        => '.col-lg-4, .grid-30, .grid-33, .grid-35,',
    '.col-lg-4 {'       => '.col-lg-4, .grid-30, .grid-33, .grid-35 {',
    '.col-lg-5,'        => '.col-lg-5, .grid-40, .grid-45,',
    '.col-lg-5 {'       => '.col-lg-5, .grid-40, .grid-45 {',
    '.col-lg-6,'        => '.col-lg-6, .grid-50,',
    '.col-lg-6 {'       => '.col-lg-6, .grid-50 {',
    '.col-lg-7,'        => '.col-lg-7, .grid-55, .grid-60,',
    '.col-lg-7 {'       => '.col-lg-7, .grid-55, .grid-60 {',
    '.col-lg-8,'        => '.col-lg-8, .grid-65, .grid-66, .grid-70,',
    '.col-lg-8 {'       => '.col-lg-8, .grid-65, .grid-66, .grid-70 {',
    '.col-lg-9,'        => '.col-lg-9, .grid-75, .grid-80,',
    '.col-lg-9 {'       => '.col-lg-9, .grid-75, .grid-80 {',
    '.col-lg-10,'       => '.col-lg-10, .grid-85,',
    '.col-lg-10 {'      => '.col-lg-10, .grid-85 {',
    '.col-lg-11,'       => '.col-lg-11, .grid-90, .grid-95,',
    '.col-lg-11 {'      => '.col-lg-11, .grid-90, .grid-95 {',
    '.col-lg-12,'       => '.col-lg-12, .grid-100,',
    '.col-lg-12 {'      => '.col-lg-12, .grid-100 {',
    // md
    '.col-md-1,'        => '.col-md-1, .grid-5, .grid-10,',
    '.col-md-1 {'       => '.col-md-1, .grid-5, .grid-10 {',
    '.col-md-2,'        => '.col-md-2, .grid-15,',
    '.col-md-2 {'       => '.col-md-2, .grid-15 {',
    '.col-md-3,'        => '.col-md-3, .grid-20, .grid-25,',
    '.col-md-3 {'       => '.col-md-3, .grid-20, .grid-25 {',
    '.col-md-4,'        => '.col-md-4, .grid-30, .grid-33, .grid-35,',
    '.col-md-4 {'       => '.col-md-4, .grid-30, .grid-33, .grid-35 {',
    '.col-md-5,'        => '.col-md-5, .grid-40, .grid-45,',
    '.col-md-5 {'       => '.col-md-5, .grid-40, .grid-45 {',
    '.col-md-6,'        => '.col-md-6, .grid-50,',
    '.col-md-6 {'       => '.col-md-6, .grid-50 {',
    '.col-md-7,'        => '.col-md-7, .grid-55, .grid-60,',
    '.col-md-7 {'       => '.col-md-7, .grid-55, .grid-60 {',
    '.col-md-8,'        => '.col-md-8, .grid-65, .grid-66, .grid-70,',
    '.col-md-8 {'       => '.col-md-8, .grid-65, .grid-66, .grid-70 {',
    '.col-md-9,'        => '.col-md-9, .grid-75, .grid-80,',
    '.col-md-9 {'       => '.col-md-9, .grid-75, .grid-80 {',
    '.col-md-10,'       => '.col-md-10, .grid-85,',
    '.col-md-10 {'      => '.col-md-10, .grid-85 {',
    '.col-md-11,'       => '.col-md-11, .grid-90, .grid-95,',
    '.col-md-11 {'      => '.col-md-11, .grid-90, .grid-95 {',
    '.col-md-12,'       => '.col-md-12, .grid-100,',
    '.col-md-12 {'      => '.col-md-12, .grid-100 {',
    // sm
    '.col-sm-1,'        => '.col-sm-1, .mobile-grid-5, .mobile-grid-10,',
    '.col-sm-1 {'       => '.col-sm-1, .mobile-grid-5, .mobile-grid-10 {',
    '.col-sm-2,'        => '.col-sm-2, .mobile-grid-15,',
    '.col-sm-2 {'       => '.col-sm-2, .mobile-grid-15 {',
    '.col-sm-3,'        => '.col-sm-3, .mobile-grid-20, .mobile-grid-25,',
    '.col-sm-3 {'       => '.col-sm-3, .mobile-grid-20, .mobile-grid-25 {',
    '.col-sm-4,'        => '.col-sm-4, .mobile-grid-30, .mobile-grid-33, .mobile-grid-35,',
    '.col-sm-4 {'       => '.col-sm-4, .mobile-grid-30, .mobile-grid-33, .mobile-grid-35 {',
    '.col-sm-5,'        => '.col-sm-5, .mobile-grid-40, .mobile-grid-45,',
    '.col-sm-5 {'       => '.col-sm-5, .mobile-grid-40, .mobile-grid-45 {',
    '.col-sm-6,'        => '.col-sm-6, .mobile-grid-50,',
    '.col-sm-6 {'       => '.col-sm-6, .mobile-grid-50 {',
    '.col-sm-7,'        => '.col-sm-7, .mobile-grid-55, .mobile-grid-60,',
    '.col-sm-7 {'       => '.col-sm-7, .mobile-grid-55, .mobile-grid-60 {',
    '.col-sm-8,'        => '.col-sm-8, .mobile-grid-65, .mobile-grid-66, .mobile-grid-70,',
    '.col-sm-8 {'       => '.col-sm-8, .mobile-grid-65, .mobile-grid-66, .mobile-grid-70 {',
    '.col-sm-9,'        => '.col-sm-9, .mobile-grid-75, .mobile-grid-80,',
    '.col-sm-9 {'       => '.col-sm-9, .mobile-grid-75, .mobile-grid-80 {',
    '.col-sm-10,'       => '.col-sm-10, .mobile-grid-85,',
    '.col-sm-10 {'      => '.col-sm-10, .mobile-grid-85 {',
    '.col-sm-11,'       => '.col-sm-11, .mobile-grid-90, .mobile-grid-95,',
    '.col-sm-11 {'      => '.col-sm-11, .mobile-grid-90, .mobile-grid-95 {',
    '.col-sm-12,'       => '.col-sm-12, .mobile-grid-100,',
    '.col-sm-12 {'      => '.col-sm-12, .mobile-grid-100 {',
    // xs
    '.col-xs-1,'        => '.col-xs-1, .mobile-grid-5, .mobile-grid-10,',
    '.col-xs-1 {'       => '.col-xs-1, .mobile-grid-5, .mobile-grid-10 {',
    '.col-xs-2,'        => '.col-xs-2, .mobile-grid-15,',
    '.col-xs-2 {'       => '.col-xs-2, .mobile-grid-15 {',
    '.col-xs-3,'        => '.col-xs-3, .mobile-grid-20, .mobile-grid-25,',
    '.col-xs-3 {'       => '.col-xs-3, .mobile-grid-20, .mobile-grid-25 {',
    '.col-xs-4,'        => '.col-xs-4, .mobile-grid-30, .mobile-grid-33, .mobile-grid-35,',
    '.col-xs-4 {'       => '.col-xs-4, .mobile-grid-30, .mobile-grid-33, .mobile-grid-35 {',
    '.col-xs-5,'        => '.col-xs-5, .mobile-grid-40, .mobile-grid-45,',
    '.col-xs-5 {'       => '.col-xs-5, .mobile-grid-40, .mobile-grid-45 {',
    '.col-xs-6,'        => '.col-xs-6, .mobile-grid-50,',
    '.col-xs-6 {'       => '.col-xs-6, .mobile-grid-50 {',
    '.col-xs-7,'        => '.col-xs-7, .mobile-grid-55, .mobile-grid-60,',
    '.col-xs-7 {'       => '.col-xs-7, .mobile-grid-55, .mobile-grid-60 {',
    '.col-xs-8,'        => '.col-xs-8, .mobile-grid-65, .mobile-grid-66, .mobile-grid-70,',
    '.col-xs-8 {'       => '.col-xs-8, .mobile-grid-65, .mobile-grid-66, .mobile-grid-70 {',
    '.col-xs-9,'        => '.col-xs-9, .mobile-grid-75, .mobile-grid-80,',
    '.col-xs-9 {'       => '.col-xs-9, .mobile-grid-75, .mobile-grid-80 {',
    '.col-xs-10,'       => '.col-xs-10, .mobile-grid-85,',
    '.col-xs-10 {'      => '.col-xs-10, .mobile-grid-85 {',
    '.col-xs-11,'       => '.col-xs-11, .mobile-grid-90, .mobile-grid-95,',
    '.col-xs-11 {'      => '.col-xs-11, .mobile-grid-90, .mobile-grid-95 {',
    '.col-xs-12,'       => '.col-xs-12, .mobile-grid-100,',
    '.col-xs-12 {'      => '.col-xs-12, .mobile-grid-100 {',
    // push lg
    '.col-lg-push-1,'   => '.col-lg-push-1, .push-5, .push-10,',
    '.col-lg-push-1 {'  => '.col-lg-push-1, .push-5, .push-10 {',
    '.col-lg-push-2,'   => '.col-lg-push-2, .push-15,',
    '.col-lg-push-2 {'  => '.col-lg-push-2, .push-15 {',
    '.col-lg-push-3,'   => '.col-lg-push-3, .push-20, .push-25,',
    '.col-lg-push-3 {'  => '.col-lg-push-3, .push-20, .push-25 {',
    '.col-lg-push-4,'   => '.col-lg-push-4, .push-30, .push-33, .push-35,',
    '.col-lg-push-4 {'  => '.col-lg-push-4, .push-30, .push-33, .push-35 {',
    '.col-lg-push-5,'   => '.col-lg-push-5, .push-40, .push-45,',
    '.col-lg-push-5 {'  => '.col-lg-push-5, .push-40, .push-45 {',
    '.col-lg-push-6,'   => '.col-lg-push-6, .push-50,',
    '.col-lg-push-6 {'  => '.col-lg-push-6, .push-50 {',
    '.col-lg-push-7,'   => '.col-lg-push-7, .push-55, .push-60,',
    '.col-lg-push-7 {'  => '.col-lg-push-7, .push-55, .push-60 {',
    '.col-lg-push-8,'   => '.col-lg-push-8, .push-65, .push-66, .push-70,',
    '.col-lg-push-8 {'  => '.col-lg-push-8, .push-65, .push-66, .push-70 {',
    '.col-lg-push-9,'   => '.col-lg-push-9, .push-75, .push-80,',
    '.col-lg-push-9 {'  => '.col-lg-push-9, .push-75, .push-80 {',
    '.col-lg-push-10,'  => '.col-lg-push-10, .push-85,',
    '.col-lg-push-10 {' => '.col-lg-push-10, .push-85 {',
    '.col-lg-push-11,'  => '.col-lg-push-11, .push-90, .push-95,',
    '.col-lg-push-11 {' => '.col-lg-push-11, .push-90, .push-95 {',
    '.col-lg-push-12,'  => '.col-lg-push-12, .push-100,',
    '.col-lg-push-12 {' => '.col-lg-push-12, .push-100 {',
    // push md
    '.col-md-push-1,'   => '.col-md-push-1, .push-5, .push-10,',
    '.col-md-push-1 {'  => '.col-md-push-1, .push-5, .push-10 {',
    '.col-md-push-2,'   => '.col-md-push-2, .push-15,',
    '.col-md-push-2 {'  => '.col-md-push-2, .push-15 {',
    '.col-md-push-3,'   => '.col-md-push-3, .push-20, .push-25,',
    '.col-md-push-3 {'  => '.col-md-push-3, .push-20, .push-25 {',
    '.col-md-push-4,'   => '.col-md-push-4, .push-30, .push-33, .push-35,',
    '.col-md-push-4 {'  => '.col-md-push-4, .push-30, .push-33, .push-35 {',
    '.col-md-push-5,'   => '.col-md-push-5, .push-40, .push-45,',
    '.col-md-push-5 {'  => '.col-md-push-5, .push-40, .push-45 {',
    '.col-md-push-6,'   => '.col-md-push-6, .push-50,',
    '.col-md-push-6 {'  => '.col-md-push-6, .push-50 {',
    '.col-md-push-7,'   => '.col-md-push-7, .push-55, .push-60,',
    '.col-md-push-7 {'  => '.col-md-push-7, .push-55, .push-60 {',
    '.col-md-push-8,'   => '.col-md-push-8, .push-65, .push-66, .push-70,',
    '.col-md-push-8 {'  => '.col-md-push-8, .push-65, .push-66, .push-70 {',
    '.col-md-push-9,'   => '.col-md-push-9, .push-75, .push-80,',
    '.col-md-push-9 {'  => '.col-md-push-9, .push-75, .push-80 {',
    '.col-md-push-10,'  => '.col-md-push-10, .push-85,',
    '.col-md-push-10 {' => '.col-md-push-10, .push-85 {',
    '.col-md-push-11,'  => '.col-md-push-11, .push-90, .push-95,',
    '.col-md-push-11 {' => '.col-md-push-11, .push-90, .push-95 {',
    '.col-md-push-12,'  => '.col-md-push-12, .push-100,',
    '.col-md-push-12 {' => '.col-md-push-12, .push-100 {',
    // push sm
    '.col-sm-push-1,'   => '.col-sm-push-1, .mobile-push-5, .mobile-push-10,',
    '.col-sm-push-1 {'  => '.col-sm-push-1, .mobile-push-5, .mobile-push-10 {',
    '.col-sm-push-2,'   => '.col-sm-push-2, .mobile-push-15,',
    '.col-sm-push-2 {'  => '.col-sm-push-2, .mobile-push-15 {',
    '.col-sm-push-3,'   => '.col-sm-push-3, .mobile-push-20, .mobile-push-25,',
    '.col-sm-push-3 {'  => '.col-sm-push-3, .mobile-push-20, .mobile-push-25 {',
    '.col-sm-push-4,'   => '.col-sm-push-4, .mobile-push-30, .mobile-push-33, .mobile-push-35,',
    '.col-sm-push-4 {'  => '.col-sm-push-4, .mobile-push-30, .mobile-push-33, .mobile-push-35 {',
    '.col-sm-push-5,'   => '.col-sm-push-5, .mobile-push-40, .mobile-push-45,',
    '.col-sm-push-5 {'  => '.col-sm-push-5, .mobile-push-40, .mobile-push-45 {',
    '.col-sm-push-6,'   => '.col-sm-push-6, .mobile-push-50,',
    '.col-sm-push-6 {'  => '.col-sm-push-6, .mobile-push-50 {',
    '.col-sm-push-7,'   => '.col-sm-push-7, .mobile-push-55, .mobile-push-60,',
    '.col-sm-push-7 {'  => '.col-sm-push-7, .mobile-push-55, .mobile-push-60 {',
    '.col-sm-push-8,'   => '.col-sm-push-8, .mobile-push-65, .mobile-push-66, .mobile-push-70,',
    '.col-sm-push-8 {'  => '.col-sm-push-8, .mobile-push-65, .mobile-push-66, .mobile-push-70 {',
    '.col-sm-push-9,'   => '.col-sm-push-9, .mobile-push-75, .mobile-push-80,',
    '.col-sm-push-9 {'  => '.col-sm-push-9, .mobile-push-75, .mobile-push-80 {',
    '.col-sm-push-10,'  => '.col-sm-push-10, .mobile-push-85,',
    '.col-sm-push-10 {' => '.col-sm-push-10, .mobile-push-85 {',
    '.col-sm-push-11,'  => '.col-sm-push-11, .mobile-push-90, .mobile-push-95,',
    '.col-sm-push-11 {' => '.col-sm-push-11, .mobile-push-90, .mobile-push-95 {',
    '.col-sm-push-12,'  => '.col-sm-push-12, .mobile-push-100,',
    '.col-sm-push-12 {' => '.col-sm-push-12, .mobile-push-100 {',
    // push xs
    '.col-xs-push-1,'   => '.col-xs-push-1, .mobile-push-5, .mobile-push-10,',
    '.col-xs-push-1 {'  => '.col-xs-push-1, .mobile-push-5, .mobile-push-10 {',
    '.col-xs-push-2,'   => '.col-xs-push-2, .mobile-push-15,',
    '.col-xs-push-2 {'  => '.col-xs-push-2, .mobile-push-15 {',
    '.col-xs-push-3,'   => '.col-xs-push-3, .mobile-push-20, .mobile-push-25,',
    '.col-xs-push-3 {'  => '.col-xs-push-3, .mobile-push-20, .mobile-push-25 {',
    '.col-xs-push-4,'   => '.col-xs-push-4, .mobile-push-30, .mobile-push-33, .mobile-push-35,',
    '.col-xs-push-4 {'  => '.col-xs-push-4, .mobile-push-30, .mobile-push-33, .mobile-push-35 {',
    '.col-xs-push-5,'   => '.col-xs-push-5, .mobile-push-40, .mobile-push-45,',
    '.col-xs-push-5 {'  => '.col-xs-push-5, .mobile-push-40, .mobile-push-45 {',
    '.col-xs-push-6,'   => '.col-xs-push-6, .mobile-push-50,',
    '.col-xs-push-6 {'  => '.col-xs-push-6, .mobile-push-50 {',
    '.col-xs-push-7,'   => '.col-xs-push-7, .mobile-push-55, .mobile-push-60,',
    '.col-xs-push-7 {'  => '.col-xs-push-7, .mobile-push-55, .mobile-push-60 {',
    '.col-xs-push-8,'   => '.col-xs-push-8, .mobile-push-65, .mobile-push-66, .mobile-push-70,',
    '.col-xs-push-8 {'  => '.col-xs-push-8, .mobile-push-65, .mobile-push-66, .mobile-push-70 {',
    '.col-xs-push-9,'   => '.col-xs-push-9, .mobile-push-75, .mobile-push-80,',
    '.col-xs-push-9 {'  => '.col-xs-push-9, .mobile-push-75, .mobile-push-80 {',
    '.col-xs-push-10,'  => '.col-xs-push-10, .mobile-push-85,',
    '.col-xs-push-10 {' => '.col-xs-push-10, .mobile-push-85 {',
    '.col-xs-push-11,'  => '.col-xs-push-11, .mobile-push-90, .mobile-push-95,',
    '.col-xs-push-11 {' => '.col-xs-push-11, .mobile-push-90, .mobile-push-95 {',
    '.col-xs-push-12,'  => '.col-xs-push-12, .mobile-push-100,',
    '.col-xs-push-12 {' => '.col-xs-push-12, .mobile-push-100 {',
    // pull lg
    '.col-lg-pull-1,'   => '.col-lg-pull-1, .pull-5, .pull-10,',
    '.col-lg-pull-1 {'  => '.col-lg-pull-1, .pull-5, .pull-10 {',
    '.col-lg-pull-2,'   => '.col-lg-pull-2, .pull-15,',
    '.col-lg-pull-2 {'  => '.col-lg-pull-2, .pull-15 {',
    '.col-lg-pull-3,'   => '.col-lg-pull-3, .pull-20, .pull-25,',
    '.col-lg-pull-3 {'  => '.col-lg-pull-3, .pull-20, .pull-25 {',
    '.col-lg-pull-4,'   => '.col-lg-pull-4, .pull-30, .pull-33, .pull-35,',
    '.col-lg-pull-4 {'  => '.col-lg-pull-4, .pull-30, .pull-33, .pull-35 {',
    '.col-lg-pull-5,'   => '.col-lg-pull-5, .pull-40, .pull-45,',
    '.col-lg-pull-5 {'  => '.col-lg-pull-5, .pull-40, .pull-45 {',
    '.col-lg-pull-6,'   => '.col-lg-pull-6, .pull-50,',
    '.col-lg-pull-6 {'  => '.col-lg-pull-6, .pull-50 {',
    '.col-lg-pull-7,'   => '.col-lg-pull-7, .pull-55, .pull-60,',
    '.col-lg-pull-7 {'  => '.col-lg-pull-7, .pull-55, .pull-60 {',
    '.col-lg-pull-8,'   => '.col-lg-pull-8, .pull-65, .pull-66, .pull-70,',
    '.col-lg-pull-8 {'  => '.col-lg-pull-8, .pull-65, .pull-66, .pull-70 {',
    '.col-lg-pull-9,'   => '.col-lg-pull-9, .pull-75, .pull-80,',
    '.col-lg-pull-9 {'  => '.col-lg-pull-9, .pull-75, .pull-80 {',
    '.col-lg-pull-10,'  => '.col-lg-pull-10, .pull-85,',
    '.col-lg-pull-10 {' => '.col-lg-pull-10, .pull-85 {',
    '.col-lg-pull-11,'  => '.col-lg-pull-11, .pull-90, .pull-95,',
    '.col-lg-pull-11 {' => '.col-lg-pull-11, .pull-90, .pull-95 {',
    '.col-lg-pull-12,'  => '.col-lg-pull-12, .pull-100,',
    '.col-lg-pull-12 {' => '.col-lg-pull-12, .pull-100 {',
    // pull md
    '.col-md-pull-1,'   => '.col-md-pull-1, .pull-5, .pull-10,',
    '.col-md-pull-1 {'  => '.col-md-pull-1, .pull-5, .pull-10 {',
    '.col-md-pull-2,'   => '.col-md-pull-2, .pull-15,',
    '.col-md-pull-2 {'  => '.col-md-pull-2, .pull-15 {',
    '.col-md-pull-3,'   => '.col-md-pull-3, .pull-20, .pull-25,',
    '.col-md-pull-3 {'  => '.col-md-pull-3, .pull-20, .pull-25 {',
    '.col-md-pull-4,'   => '.col-md-pull-4, .pull-30, .pull-33, .pull-35,',
    '.col-md-pull-4 {'  => '.col-md-pull-4, .pull-30, .pull-33, .pull-35 {',
    '.col-md-pull-5,'   => '.col-md-pull-5, .pull-40, .pull-45,',
    '.col-md-pull-5 {'  => '.col-md-pull-5, .pull-40, .pull-45 {',
    '.col-md-pull-6,'   => '.col-md-pull-6, .pull-50,',
    '.col-md-pull-6 {'  => '.col-md-pull-6, .pull-50 {',
    '.col-md-pull-7,'   => '.col-md-pull-7, .pull-55, .pull-60,',
    '.col-md-pull-7 {'  => '.col-md-pull-7, .pull-55, .pull-60 {',
    '.col-md-pull-8,'   => '.col-md-pull-8, .pull-65, .pull-66, .pull-70,',
    '.col-md-pull-8 {'  => '.col-md-pull-8, .pull-65, .pull-66, .pull-70 {',
    '.col-md-pull-9,'   => '.col-md-pull-9, .pull-75, .pull-80,',
    '.col-md-pull-9 {'  => '.col-md-pull-9, .pull-75, .pull-80 {',
    '.col-md-pull-10,'  => '.col-md-pull-10, .pull-85,',
    '.col-md-pull-10 {' => '.col-md-pull-10, .pull-85 {',
    '.col-md-pull-11,'  => '.col-md-pull-11, .pull-90, .pull-95,',
    '.col-md-pull-11 {' => '.col-md-pull-11, .pull-90, .pull-95 {',
    '.col-md-pull-12,'  => '.col-md-pull-12, .pull-100,',
    '.col-md-pull-12 {' => '.col-md-pull-12, .pull-100 {',
    // pull sm
    '.col-sm-pull-1,'   => '.col-sm-pull-1, .mobile-pull-5, .mobile-pull-10,',
    '.col-sm-pull-1 {'  => '.col-sm-pull-1, .mobile-pull-5, .mobile-pull-10 {',
    '.col-sm-pull-2,'   => '.col-sm-pull-2, .mobile-pull-15,',
    '.col-sm-pull-2 {'  => '.col-sm-pull-2, .mobile-pull-15 {',
    '.col-sm-pull-3,'   => '.col-sm-pull-3, .mobile-pull-20, .mobile-pull-25,',
    '.col-sm-pull-3 {'  => '.col-sm-pull-3, .mobile-pull-20, .mobile-pull-25 {',
    '.col-sm-pull-4,'   => '.col-sm-pull-4, .mobile-pull-30, .mobile-pull-33, .mobile-pull-35,',
    '.col-sm-pull-4 {'  => '.col-sm-pull-4, .mobile-pull-30, .mobile-pull-33, .mobile-pull-35 {',
    '.col-sm-pull-5,'   => '.col-sm-pull-5, .mobile-pull-40, .mobile-pull-45,',
    '.col-sm-pull-5 {'  => '.col-sm-pull-5, .mobile-pull-40, .mobile-pull-45 {',
    '.col-sm-pull-6,'   => '.col-sm-pull-6, .mobile-pull-50,',
    '.col-sm-pull-6 {'  => '.col-sm-pull-6, .mobile-pull-50 {',
    '.col-sm-pull-7,'   => '.col-sm-pull-7, .mobile-pull-55, .mobile-pull-60,',
    '.col-sm-pull-7 {'  => '.col-sm-pull-7, .mobile-pull-55, .mobile-pull-60 {',
    '.col-sm-pull-8,'   => '.col-sm-pull-8, .mobile-pull-65, .mobile-pull-66, .mobile-pull-70,',
    '.col-sm-pull-8 {'  => '.col-sm-pull-8, .mobile-pull-65, .mobile-pull-66, .mobile-pull-70 {',
    '.col-sm-pull-9,'   => '.col-sm-pull-9, .mobile-pull-75, .mobile-pull-80,',
    '.col-sm-pull-9 {'  => '.col-sm-pull-9, .mobile-pull-75, .mobile-pull-80 {',
    '.col-sm-pull-10,'  => '.col-sm-pull-10, .mobile-pull-85,',
    '.col-sm-pull-10 {' => '.col-sm-pull-10, .mobile-pull-85 {',
    '.col-sm-pull-11,'  => '.col-sm-pull-11, .mobile-pull-90, .mobile-pull-95,',
    '.col-sm-pull-11 {' => '.col-sm-pull-11, .mobile-pull-90, .mobile-pull-95 {',
    '.col-sm-pull-12,'  => '.col-sm-pull-12, .mobile-pull-100,',
    '.col-sm-pull-12 {' => '.col-sm-pull-12, .mobile-pull-100 {',
    // pull xs
    '.col-xs-pull-1,'   => '.col-xs-pull-1, .mobile-pull-5, .mobile-pull-10,',
    '.col-xs-pull-1 {'  => '.col-xs-pull-1, .mobile-pull-5, .mobile-pull-10 {',
    '.col-xs-pull-2,'   => '.col-xs-pull-2, .mobile-pull-15,',
    '.col-xs-pull-2 {'  => '.col-xs-pull-2, .mobile-pull-15 {',
    '.col-xs-pull-3,'   => '.col-xs-pull-3, .mobile-pull-20, .mobile-pull-25,',
    '.col-xs-pull-3 {'  => '.col-xs-pull-3, .mobile-pull-20, .mobile-pull-25 {',
    '.col-xs-pull-4,'   => '.col-xs-pull-4, .mobile-pull-30, .mobile-pull-33, .mobile-pull-35,',
    '.col-xs-pull-4 {'  => '.col-xs-pull-4, .mobile-pull-30, .mobile-pull-33, .mobile-pull-35 {',
    '.col-xs-pull-5,'   => '.col-xs-pull-5, .mobile-pull-40, .mobile-pull-45,',
    '.col-xs-pull-5 {'  => '.col-xs-pull-5, .mobile-pull-40, .mobile-pull-45 {',
    '.col-xs-pull-6,'   => '.col-xs-pull-6, .mobile-pull-50,',
    '.col-xs-pull-6 {'  => '.col-xs-pull-6, .mobile-pull-50 {',
    '.col-xs-pull-7,'   => '.col-xs-pull-7, .mobile-pull-55, .mobile-pull-60,',
    '.col-xs-pull-7 {'  => '.col-xs-pull-7, .mobile-pull-55, .mobile-pull-60 {',
    '.col-xs-pull-8,'   => '.col-xs-pull-8, .mobile-pull-65, .mobile-pull-66, .mobile-pull-70,',
    '.col-xs-pull-8 {'  => '.col-xs-pull-8, .mobile-pull-65, .mobile-pull-66, .mobile-pull-70 {',
    '.col-xs-pull-9,'   => '.col-xs-pull-9, .mobile-pull-75, .mobile-pull-80,',
    '.col-xs-pull-9 {'  => '.col-xs-pull-9, .mobile-pull-75, .mobile-pull-80 {',
    '.col-xs-pull-10,'  => '.col-xs-pull-10, .mobile-pull-85,',
    '.col-xs-pull-10 {' => '.col-xs-pull-10, .mobile-pull-85 {',
    '.col-xs-pull-11,'  => '.col-xs-pull-11, .mobile-pull-90, .mobile-pull-95,',
    '.col-xs-pull-11 {' => '.col-xs-pull-11, .mobile-pull-90, .mobile-pull-95 {',
    '.col-xs-pull-12,'  => '.col-xs-pull-12, .mobile-pull-100,',
    '.col-xs-pull-12 {' => '.col-xs-pull-12, .mobile-pull-100 {',
];

$extras = '
.grid-parent {
    padding-left: 0;
    padding-right: 0;
}
@media (min-width: 768px) {
    .hide-on-desktop {
        display: none !important;
    }
}
@media (max-width: 767px) {
    .hide-on-mobile {
        display: none !important;
    }
}

.push-5, .pull-5, .push-10, .pull-10, .push-15, .pull-15, .push-20, .pull-20, .push-25, .pull-25, .push-30, .pull-30, .push-35, .pull-35, .push-40, .pull-40, .push-45, .pull-45, .push-50, .pull-50, .push-55, .pull-55, .push-60, .pull-60, .push-65, .pull-65, .push-70, .pull-70, .push-75, .pull-75, .push-80, .pull-80, .push-85, .pull-85, .push-90, .pull-90, .push-95, .pull-95, .push-33, .pull-33, .push-66, .pull-66 {
    position: relative;
}
';