<?php

$relation = [
    'extras'       => '

.grid-parent {
    padding-left: 0;
    padding-right: 0;
}
@media (min-width: 768px) {
    .hide-on-desktop {
        display: none !important;
    }
}
@media (max-width: 767px) {
    .hide-on-mobile {
        display: none !important;
    }
}

',
    'otherClasses' => [
        '.grid-container' => '.container',
        '.grid-offset'    => '.row'
    ],
    'lg'           => [
        '.grid-5'   => '.col-lg-1',
        '.grid-10'  => '.col-lg-1',
        '.grid-15'  => '.col-lg-2',
        '.grid-20'  => '.col-lg-3',
        '.grid-25'  => '.col-lg-3',
        '.grid-30'  => '.col-lg-4',
        '.grid-33'  => '.col-lg-4',
        '.grid-35'  => '.col-lg-4',
        '.grid-40'  => '.col-lg-5',
        '.grid-45'  => '.col-lg-5',
        '.grid-50'  => '.col-lg-6',
        '.grid-55'  => '.col-lg-7',
        '.grid-60'  => '.col-lg-7',
        '.grid-65'  => '.col-lg-8',
        '.grid-66'  => '.col-lg-8',
        '.grid-70'  => '.col-lg-8',
        '.grid-75'  => '.col-lg-9',
        '.grid-80'  => '.col-lg-9',
        '.grid-85'  => '.col-lg-10',
        '.grid-90'  => '.col-lg-11',
        '.grid-95'  => '.col-lg-11',
        '.grid-100' => '.col-lg-12'
    ],
    'md'           => [
        '.grid-5'   => '.col-md-1',
        '.grid-10'  => '.col-md-1',
        '.grid-15'  => '.col-md-2',
        '.grid-20'  => '.col-md-3',
        '.grid-25'  => '.col-md-3',
        '.grid-30'  => '.col-md-4',
        '.grid-33'  => '.col-md-4',
        '.grid-35'  => '.col-md-4',
        '.grid-40'  => '.col-md-5',
        '.grid-45'  => '.col-md-5',
        '.grid-50'  => '.col-md-6',
        '.grid-55'  => '.col-md-7',
        '.grid-60'  => '.col-md-7',
        '.grid-65'  => '.col-md-8',
        '.grid-66'  => '.col-md-8',
        '.grid-70'  => '.col-md-8',
        '.grid-75'  => '.col-md-9',
        '.grid-80'  => '.col-md-9',
        '.grid-85'  => '.col-md-10',
        '.grid-90'  => '.col-md-11',
        '.grid-95'  => '.col-md-11',
        '.grid-100' => '.col-md-12'
    ],
    'sm'           => [
        '.mobile-grid-5'   => '.col-sm-1',
        '.mobile-grid-10'  => '.col-sm-1',
        '.mobile-grid-15'  => '.col-sm-2',
        '.mobile-grid-20'  => '.col-sm-3',
        '.mobile-grid-25'  => '.col-sm-3',
        '.mobile-grid-30'  => '.col-sm-4',
        '.mobile-grid-33'  => '.col-sm-4',
        '.mobile-grid-35'  => '.col-sm-4',
        '.mobile-grid-40'  => '.col-sm-5',
        '.mobile-grid-45'  => '.col-sm-5',
        '.mobile-grid-50'  => '.col-sm-6',
        '.mobile-grid-55'  => '.col-sm-7',
        '.mobile-grid-60'  => '.col-sm-7',
        '.mobile-grid-65'  => '.col-sm-8',
        '.mobile-grid-66'  => '.col-sm-8',
        '.mobile-grid-70'  => '.col-sm-8',
        '.mobile-grid-75'  => '.col-sm-9',
        '.mobile-grid-80'  => '.col-sm-9',
        '.mobile-grid-85'  => '.col-sm-10',
        '.mobile-grid-90'  => '.col-sm-11',
        '.mobile-grid-95'  => '.col-sm-11',
        '.mobile-grid-100' => '.col-sm-12'
    ],
    'xs'           => [
        '.mobile-grid-5'   => '.col-xs-1',
        '.mobile-grid-10'  => '.col-xs-1',
        '.mobile-grid-15'  => '.col-xs-2',
        '.mobile-grid-20'  => '.col-xs-3',
        '.mobile-grid-25'  => '.col-xs-3',
        '.mobile-grid-30'  => '.col-xs-4',
        '.mobile-grid-33'  => '.col-xs-4',
        '.mobile-grid-35'  => '.col-xs-4',
        '.mobile-grid-40'  => '.col-xs-5',
        '.mobile-grid-45'  => '.col-xs-5',
        '.mobile-grid-50'  => '.col-xs-6',
        '.mobile-grid-55'  => '.col-xs-7',
        '.mobile-grid-60'  => '.col-xs-7',
        '.mobile-grid-65'  => '.col-xs-8',
        '.mobile-grid-66'  => '.col-xs-8',
        '.mobile-grid-70'  => '.col-xs-8',
        '.mobile-grid-75'  => '.col-xs-9',
        '.mobile-grid-80'  => '.col-xs-9',
        '.mobile-grid-85'  => '.col-xs-10',
        '.mobile-grid-90'  => '.col-xs-11',
        '.mobile-grid-95'  => '.col-xs-11',
        '.mobile-grid-100' => '.col-xs-12'
    ],
    'push lg'      => [
        '.push-5'   => '.col-lg-push-1',
        '.push-10'  => '.col-lg-push-1',
        '.push-15'  => '.col-lg-push-2',
        '.push-20'  => '.col-lg-push-3',
        '.push-25'  => '.col-lg-push-3',
        '.push-30'  => '.col-lg-push-4',
        '.push-33'  => '.col-lg-push-4',
        '.push-35'  => '.col-lg-push-4',
        '.push-40'  => '.col-lg-push-5',
        '.push-45'  => '.col-lg-push-5',
        '.push-50'  => '.col-lg-push-6',
        '.push-55'  => '.col-lg-push-7',
        '.push-60'  => '.col-lg-push-7',
        '.push-65'  => '.col-lg-push-8',
        '.push-66'  => '.col-lg-push-8',
        '.push-70'  => '.col-lg-push-8',
        '.push-75'  => '.col-lg-push-9',
        '.push-80'  => '.col-lg-push-9',
        '.push-85'  => '.col-lg-push-10',
        '.push-90'  => '.col-lg-push-11',
        '.push-95'  => '.col-lg-push-11',
        '.push-100' => '.col-lg-push-12'
    ],
    'push md'      => [
        '.push-5'   => '.col-md-push-1',
        '.push-10'  => '.col-md-push-1',
        '.push-15'  => '.col-md-push-2',
        '.push-20'  => '.col-md-push-3',
        '.push-25'  => '.col-md-push-3',
        '.push-30'  => '.col-md-push-4',
        '.push-33'  => '.col-md-push-4',
        '.push-35'  => '.col-md-push-4',
        '.push-40'  => '.col-md-push-5',
        '.push-45'  => '.col-md-push-5',
        '.push-50'  => '.col-md-push-6',
        '.push-55'  => '.col-md-push-7',
        '.push-60'  => '.col-md-push-7',
        '.push-65'  => '.col-md-push-8',
        '.push-66'  => '.col-md-push-8',
        '.push-70'  => '.col-md-push-8',
        '.push-75'  => '.col-md-push-9',
        '.push-80'  => '.col-md-push-9',
        '.push-85'  => '.col-md-push-10',
        '.push-90'  => '.col-md-push-11',
        '.push-95'  => '.col-md-push-11',
        '.push-100' => '.col-md-push-12'
    ],
    'push sm'      => [
        '.mobile-push-5'   => '.col-sm-push-1',
        '.mobile-push-10'  => '.col-sm-push-1',
        '.mobile-push-15'  => '.col-sm-push-2',
        '.mobile-push-20'  => '.col-sm-push-3',
        '.mobile-push-25'  => '.col-sm-push-3',
        '.mobile-push-30'  => '.col-sm-push-4',
        '.mobile-push-33'  => '.col-sm-push-4',
        '.mobile-push-35'  => '.col-sm-push-4',
        '.mobile-push-40'  => '.col-sm-push-5',
        '.mobile-push-45'  => '.col-sm-push-5',
        '.mobile-push-50'  => '.col-sm-push-6',
        '.mobile-push-55'  => '.col-sm-push-7',
        '.mobile-push-60'  => '.col-sm-push-7',
        '.mobile-push-65'  => '.col-sm-push-8',
        '.mobile-push-66'  => '.col-sm-push-8',
        '.mobile-push-70'  => '.col-sm-push-8',
        '.mobile-push-75'  => '.col-sm-push-9',
        '.mobile-push-80'  => '.col-sm-push-9',
        '.mobile-push-85'  => '.col-sm-push-10',
        '.mobile-push-90'  => '.col-sm-push-11',
        '.mobile-push-95'  => '.col-sm-push-11',
        '.mobile-push-100' => '.col-sm-push-12'
    ],
    'push xs'      => [
        '.mobile-push-5'   => '.col-xs-push-1',
        '.mobile-push-10'  => '.col-xs-push-1',
        '.mobile-push-15'  => '.col-xs-push-2',
        '.mobile-push-20'  => '.col-xs-push-3',
        '.mobile-push-25'  => '.col-xs-push-3',
        '.mobile-push-30'  => '.col-xs-push-4',
        '.mobile-push-33'  => '.col-xs-push-4',
        '.mobile-push-35'  => '.col-xs-push-4',
        '.mobile-push-40'  => '.col-xs-push-5',
        '.mobile-push-45'  => '.col-xs-push-5',
        '.mobile-push-50'  => '.col-xs-push-6',
        '.mobile-push-55'  => '.col-xs-push-7',
        '.mobile-push-60'  => '.col-xs-push-7',
        '.mobile-push-65'  => '.col-xs-push-8',
        '.mobile-push-66'  => '.col-xs-push-8',
        '.mobile-push-70'  => '.col-xs-push-8',
        '.mobile-push-75'  => '.col-xs-push-9',
        '.mobile-push-80'  => '.col-xs-push-9',
        '.mobile-push-85'  => '.col-xs-push-10',
        '.mobile-push-90'  => '.col-xs-push-11',
        '.mobile-push-95'  => '.col-xs-push-11',
        '.mobile-push-100' => '.col-xs-push-12'
    ],
    'pull lg'      => [
        '.pull-5'   => '.col-lg-pull-1',
        '.pull-10'  => '.col-lg-pull-1',
        '.pull-15'  => '.col-lg-pull-2',
        '.pull-20'  => '.col-lg-pull-3',
        '.pull-25'  => '.col-lg-pull-3',
        '.pull-30'  => '.col-lg-pull-4',
        '.pull-33'  => '.col-lg-pull-4',
        '.pull-35'  => '.col-lg-pull-4',
        '.pull-40'  => '.col-lg-pull-5',
        '.pull-45'  => '.col-lg-pull-5',
        '.pull-50'  => '.col-lg-pull-6',
        '.pull-55'  => '.col-lg-pull-7',
        '.pull-60'  => '.col-lg-pull-7',
        '.pull-65'  => '.col-lg-pull-8',
        '.pull-66'  => '.col-lg-pull-8',
        '.pull-70'  => '.col-lg-pull-8',
        '.pull-75'  => '.col-lg-pull-9',
        '.pull-80'  => '.col-lg-pull-9',
        '.pull-85'  => '.col-lg-pull-10',
        '.pull-90'  => '.col-lg-pull-11',
        '.pull-95'  => '.col-lg-pull-11',
        '.pull-100' => '.col-lg-pull-12'
    ],
    'pull md'      => [
        '.pull-5'   => '.col-md-pull-1',
        '.pull-10'  => '.col-md-pull-1',
        '.pull-15'  => '.col-md-pull-2',
        '.pull-20'  => '.col-md-pull-3',
        '.pull-25'  => '.col-md-pull-3',
        '.pull-30'  => '.col-md-pull-4',
        '.pull-33'  => '.col-md-pull-4',
        '.pull-35'  => '.col-md-pull-4',
        '.pull-40'  => '.col-md-pull-5',
        '.pull-45'  => '.col-md-pull-5',
        '.pull-50'  => '.col-md-pull-6',
        '.pull-55'  => '.col-md-pull-7',
        '.pull-60'  => '.col-md-pull-7',
        '.pull-65'  => '.col-md-pull-8',
        '.pull-66'  => '.col-md-pull-8',
        '.pull-70'  => '.col-md-pull-8',
        '.pull-75'  => '.col-md-pull-9',
        '.pull-80'  => '.col-md-pull-9',
        '.pull-85'  => '.col-md-pull-10',
        '.pull-90'  => '.col-md-pull-11',
        '.pull-95'  => '.col-md-pull-11',
        '.pull-100' => '.col-md-pull-12'
    ],
    'pull sm'      => [
        '.mobile-pull-5'   => '.col-sm-pull-1',
        '.mobile-pull-10'  => '.col-sm-pull-1',
        '.mobile-pull-15'  => '.col-sm-pull-2',
        '.mobile-pull-20'  => '.col-sm-pull-3',
        '.mobile-pull-25'  => '.col-sm-pull-3',
        '.mobile-pull-30'  => '.col-sm-pull-4',
        '.mobile-pull-33'  => '.col-sm-pull-4',
        '.mobile-pull-35'  => '.col-sm-pull-4',
        '.mobile-pull-40'  => '.col-sm-pull-5',
        '.mobile-pull-45'  => '.col-sm-pull-5',
        '.mobile-pull-50'  => '.col-sm-pull-6',
        '.mobile-pull-55'  => '.col-sm-pull-7',
        '.mobile-pull-60'  => '.col-sm-pull-7',
        '.mobile-pull-65'  => '.col-sm-pull-8',
        '.mobile-pull-66'  => '.col-sm-pull-8',
        '.mobile-pull-70'  => '.col-sm-pull-8',
        '.mobile-pull-75'  => '.col-sm-pull-9',
        '.mobile-pull-80'  => '.col-sm-pull-9',
        '.mobile-pull-85'  => '.col-sm-pull-10',
        '.mobile-pull-90'  => '.col-sm-pull-11',
        '.mobile-pull-95'  => '.col-sm-pull-11',
        '.mobile-pull-100' => '.col-sm-pull-12'
    ],
    'pull xs'      => [
        '.mobile-pull-5'   => '.col-xs-pull-1',
        '.mobile-pull-10'  => '.col-xs-pull-1',
        '.mobile-pull-15'  => '.col-xs-pull-2',
        '.mobile-pull-20'  => '.col-xs-pull-3',
        '.mobile-pull-25'  => '.col-xs-pull-3',
        '.mobile-pull-30'  => '.col-xs-pull-4',
        '.mobile-pull-33'  => '.col-xs-pull-4',
        '.mobile-pull-35'  => '.col-xs-pull-4',
        '.mobile-pull-40'  => '.col-xs-pull-5',
        '.mobile-pull-45'  => '.col-xs-pull-5',
        '.mobile-pull-50'  => '.col-xs-pull-6',
        '.mobile-pull-55'  => '.col-xs-pull-7',
        '.mobile-pull-60'  => '.col-xs-pull-7',
        '.mobile-pull-65'  => '.col-xs-pull-8',
        '.mobile-pull-66'  => '.col-xs-pull-8',
        '.mobile-pull-70'  => '.col-xs-pull-8',
        '.mobile-pull-75'  => '.col-xs-pull-9',
        '.mobile-pull-80'  => '.col-xs-pull-9',
        '.mobile-pull-85'  => '.col-xs-pull-10',
        '.mobile-pull-90'  => '.col-xs-pull-11',
        '.mobile-pull-95'  => '.col-xs-pull-11',
        '.mobile-pull-100' => '.col-xs-pull-12'
    ],
];
